language: clojure
lein: lein2
jdk:
  - oraclejdk8
addons:
  firefox: latest
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xvfb chromium-browser
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: lein2 do deep-clean, test-advanced
